name: eventorize_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0 
  equatable: ^2.0.5
  get_it: ^7.7.0 
  intl: ^0.20.2
  floor: ^1.5.0
  flutter_hooks: ^0.21.0
  cached_network_image: ^3.4.1 
  dio: ^5.7.0  
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.10+1
  logger: ^2.0.2
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.0.0
  go_router: ^14.2.0
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  path_provider: ^2.1.4
  toastification: ^2.0.0
  google_sign_in: 6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  
  retrofit: ^4.4.0  
  retrofit_generator: ^9.1.9  
  floor_generator: ^1.5.0
  build_runner: ^2.4.13  
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_eventorize.png"
  

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
        - asset: assets/fonts/Raleway-Italic-VariableFont_wght.ttf
          style: italic      

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
          
          


    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf

  assets:
  - assets/icons/logo_google.png
  - .env/dev.env
  - assets/images/verify.png