name: eventorize_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3 
  equatable: ^2.0.5
  get_it: ^8.0.3
  intl: ^0.20.2
  floor: ^1.5.0
  flutter_hooks: ^0.21.0  
  cached_network_image: ^3.3.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8  
  floor_generator: ^1.5.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
